### ISSUE TITLE
still available?

### ISSUE THREAD

**Issue by marcus-sds** [jim80net/bosh-joyent-cpi-release#1]
Is this cpi available?

**Comment by jim80net** [comment]
Sorry Marcus, this CPI was hastily put together for a hackday project. It was not developed further than creating and deleting a VM. It has not been looked at since, unfortunately. As this project is essentially a dirty fork of the GCP CPI, there's not a lot of useful code here.  

Therefore, I'll be deleting this repo, to avoid any confusion moving forward.
